ptomasroos/react-native-multi-slider

MultiSlider.js
If the `values` prop changes in the parent component this will trigger the appropriate state change internally.
=> Handle necessary state changes with `componentWillReceiveProps`

MultiSlider.js
Hey, I am using this component in one of my projects and I had sliderLength calculated dynamically and this component were not updating positions of markers. Hence I made these changes.
=> checking sliderLength change on componentWillReceiveProps

DefaultMarker.js, MultiSlider.js
=> view prop types

MultiSlider.js
=> Added props markerOffsetX and markerOffsetY.

MultiSlider.js, example/.babelrc, example/.flowconfig, example/.gitattributes, example/.gitignore, example/Example.js, example/android/app/BUCK, example/android/app/build.gradle, example/android/app/proguard-rules.pro, example/android/app/src/main/AndroidManifest.xml, example/android/app/src/main/java/com/example/MainApplication.java, example/android/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties, example/android/keystores/BUCK, example/app.json, example/ios/example-tvOS/Info.plist, example/ios/example-tvOSTests/Info.plist, example/ios/example.xcodeproj/project.pbxproj, example/ios/example.xcodeproj/xcshareddata/xcschemes/example-tvOS.xcscheme, example/ios/example/AppDelegate.m, example/ios/exampleTests/exampleTests.m, example/package.json
=> [feature] Update example with RN 0.46; overlapping for markers/values; snap effect + [fix] Unreachable onValuesChangeStart

DefaultMarker.js, MultiSlider.js
Hi there,
I needed the markerContainter to wrap my marker, so I added the markerContainerStyle props. This works for me now, but now I need to make sure that the markerContainer's height is same or larger than my DefaultMarker's height. Any chance you can fix the container so that it'll wrap the marker nicely?
=> Add markerContainerStyle

MultiSlider.js, converters.js
fix #46
- modernize converters code
- valueToPosition uses closest index function
- improve cWRP to handle min, max properly changes
=> Improve multislider

converters.js
Fix index calculation to convert value to position correctly.
Closes #49
=> Fix valueToPosition converter

converters.js
it doesn't work on android in production mode
new impl not that easy for dummies like me
=> return old createArray implementation

MultiSlider.js
this will make the slider work in RTL apps too.
=> add RTL support

MultiSlider.js
The slider itSelf needs to be centered in vertical direction.
=> Vertically centered slider

MultiSlider.js
Usage: 
```
<MultiSlider vertical />
```
Example:
=> Added prop to make slider vertical

README.md
Updated the documentation, feel free to contribute more!
#36
=> Updated props documentation

README.md
=> Fixes path to Example-App in README

DefaultLabel.js, MultiSlider.js
=> Dynamic Label

MultiSlider.js
Make the markers move when gesturing on the selected track
=> Add touch support on selected track

DefaultMarker.js, MultiSlider.js
This would be very useful to me, and I think others might find it useful as well. Thanks!
=> add disabledMarkerStyle prop for custom styling of disabled marker

MultiSlider.js
This PR removes a duplicate track that was causing #135.
Closes #135
=> Remove duplicate track.

MultiSlider.js
Tries to resolve the issue brought in #155
=> Removed getDerivedState -> componentDidUpdate

index.d.ts
Just adding missing prop to types.
=> Add `vertical` to type definitions

README.md
Small question, when should we expect a release?
oh, I've noticed there's the same PR here: #175
=> Add `vertical` prop to readme

README.md
I found that this component has the props of vertical. So I added it
it work well
=> update the docs

MultiSlider.js
=> Fix labels

README.md
Cleaned up indentations while keeping original code style
=> Clean up indentations

MultiSlider.js, README.md, index.d.ts
* Added so its possible to show steps 
- Show step labels
- Show step marks on the track
- Customizable step labels, prefix and suffix styling etc.
- Customizable styling for step container, step label and step markers
* Added smooth-snapped
* Added docs
Issue #149 
Reference image:
=> Feature - Adding step labeling
